openapi: 3.0.4
info:
  title: PhotoSync API
  description: API for uploading, editing and accessing photos.
  version: 0.1.0
  contact:
    name: Mateusz Piętka
    email: matipietka@gmail.com
servers:
  - url: /v1
    description: locally deployed server
paths:
  /login:
    post:
      summary: logins user into API
      requestBody:
        description: user credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        "200":
          description: user successfully logged in
          content:
            text/plain:
              schema:
                type: string
                description: JWT containing user details and expiration time
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmF0aW9uX3RpbWUiOjE3NTAyNDI1NTMsInVzZXJuYW1lIjoidXNlcm5hbWVfNzY1In0.wDXirYK9DaQyzmWJ7O0b4yQ2ug8avLEAkNqy2QKNWgU
        "400":
          description: invalid request
        "401":
          description: user does not exist or invalid password was given
        "500":
          description: server error

  /register:
    post:
      summary: registers user on the server
      requestBody:
        description: user credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        "200":
          description: user successfully registered
        "400":
          description: invalid request
        "401":
          description: user already exists
        "500":
          description: server error

  /upload:
    post:
      summary: uploads a photo to a server 
      requestBody:
        description: contains the filename and modification date from the client's file system and the file itself
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  example: cat.jpg
                modification_date:
                  type: string
                  example: "2025.05.16 12:30:45"
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: image/jpeg
      responses:
        "200":
          description: photo successfully uploaded
          content:
            text/plain:
              schema:
                type: integer
                description: identifier of the photo on the server
                example: 102

components:
  schemas:
    UserCredentials:
      type: object
      properties:
        username:
          type: string
          example: username
        password:
          type: string
          example: password