# https://swagger.io/docs/specification/v3_0/about/
openapi: 3.0.4
info:
  title: Photo storage API
  description: API for uploading, editing, accessing photos.
  version: 0.0.1
  contact:
    name: Mateusz Piętka
    email: matipietka@gmail.com
servers:
  - url: /v1
    description: locally deployed server
paths:
  /photo:
    summary: endpoint for accessing photos
    parameters:
      - in: cookie
        name: userToken
        description: user authentication token
        schema:
          type: integer
        required: true
    get:
      summary: get ids of photos
      parameters:
        - in: query
          name: offset
          description: after which position start collecting photos
          schema:
            type: integer
            default: 0
            minimum: 0
        - in: query
          name: count
          description: how many photos should be returned
          schema:
            type: integer
            default: 1
            minimum: 1
      responses:
        200:
          description: OK
    post:
      summary: upload new photo to server
      requestBody:
        content:
            image/*:
              schema:
                $ref: "#/components/schemas/Image"
      responses:
        200:
          description: OK
  /photo/{id}:
    summary: tak
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
    get:
      summary: get
      responses:
        200:
          description: ok
components:
  schemas:
    Image:
      type: string
      format: binary